not_an_error = 1

main () =
    // Not a name resolution error at least. This isn't testing the type checker
    not_an_error is_an_error

    fn a b -> a + c + b

foo a b =
    bar c d =
        b

    ()

a = 2
a = 3 // already declared

// args: --show-resolved
// expected stdout:
// // id = c1m416_9923
// not_an_error_c1m416_9923 = 1
// 
// // id = c1m416_1944
// main_c1m416_1944 () =
//     not_an_error_c1m416_9923 is_an_error_?
//     fn a_4 b_5 -> +_? (+_? a_4 c_?) b_5
// 
// // id = c1m416_3132
// foo_c1m416_3132 a_1 b_2 =
//     bar_? c_? d_? =
//         b_?
//     ()
// 
// // id = c1m416_7365
// a_c1m416_7365 = 2
// 
// // id = c1m416_4138
// a_c1m416_7365 = 3

// expected stderr:
// examples/nameresolution/errors.an:5:17	error: `is_an_error` is not defined, was it a typo?
//     not_an_error is_an_error
// 
// examples/nameresolution/errors.an:7:16	error: `+` is not defined, was it a typo?
//     fn a b -> a + c + b
// 
// examples/nameresolution/errors.an:7:18	error: `c` is not defined, was it a typo?
//     fn a b -> a + c + b
// 
// examples/nameresolution/errors.an:7:20	error: `+` is not defined, was it a typo?
//     fn a b -> a + c + b
// 
// examples/nameresolution/errors.an:16:0	warning: `a` was already defined
// a = 3 // already declared
// 
// examples/nameresolution/errors.an:16:6	error: Expected a newline after the top level item but found //// already declared
// a = 3 // already declared

